BASE:
  dev:
    agw-url: "https://gdhscf-agw.lianyirong.com.cn/"
    sp-url: "https://gdhscf-sp.lianyirong.com.cn/"
    redis-url: "dev-redis.lls.com"
    redis-db: 116
    agw_message:
      username: "13611113333"
      password: "pNuyA/NW0/XwPqb7m1X5slil21SAAQFtKp13+iFQnPaSQsOPYdvx3ikE5nJOYH7QFNzNimVlWM4qeIVOaB+Zo2bluNaI4+TQWSGO7aUxe2yd31bnSEepp9v4EcRxkuSdM4tHN+306mX99tnrfRUWSUAoTOFqEz8KhAglSnYaaZKR5snVBDLrpLmf9HSu6H3W8SpNDJZNE99uSedrPAvtxbQI270qovj6eGqn4dZuHReViNnXXikbuwMXyFQhrwEzGfTCxfvYyqGmrnLnTXghWY16JvDioWKZSzd8VEXtlB56VDCUOQQA+zDRZRK8s8oBM4DiGNsf8YDuPXy3ix3QyA=="
    sp_qy_message:
      username: "13800661776"
      password: "YzKqUXCqfyLh5jxahuAoOOXtTIw7Nivf/eS3NUEuSUALz9GkXruQR/+4EDhDwmmTf43KkKNP9Zu7BCwV0GNoYlYuRgowqidZDJA8IrlqfQJFbodVaCchNHHBMtteCB4K8gt/r5HgC3lqvCZPLQhLJ2bGkcAaNjiVCpKoDm2p/8OM94XgsvgPqzgONq/Q6VawdGO3MwuX+rNln1NyWQM7gkxzX3liLkPrTZYrqQtnK4gESbW+afhYBwk0UXYDmDfMF1CZQDzXYjvxf88M/RxdqT8enl6HVXkoFiIhebNmtNdOUozUjkMlLo00f64Oc4QuLCYtDqGaBNpVTodXpeVoNw=="

    limit-web:
      limit-info: {
                      "companyId":"1650386669742587906",
                      "companyType":"CORE",
                      "companyRole":null,
                      "applyLimitName":"tyl测试开单额度",
                      "limitType":"billCredit",
                      "applyAmount":"50000000",
                      "startDate":"2023-11-14",
                      "expireDate":"2024-11-30",
                      "dataChangeHash":"f1781utl",
                      "creditPeriod":"383",
                      "companyName":"tyl核心企业",
                      "relateLimitCompanyId":"0",
                      "limitTypeName":"开单额度",
                      "applyType":"NEW"
                  }
    asset-info: {
                      "initiatingSystem":"供应链系统",
                      "assetNo":null,
                      "coreCompany":"tyl核心企业",
                      "supplierId":"1650386718794973185",
                      "assetAmount":"1000",
                      "assetDueDate":"2023-11-30",
                      "newDate":"2023-11-14",
                      "assetContractDTOList":null,
                      "dataChangeHash":"f2dcfuki",
                      "assetDueDayNum":"16",
                      "supplier":"tyl供应商"
                  }
  qa:
    agw-url: "https://gdhscf-agw.qhhrly.cn/"
    sp-url: "https://gdhscf-sp.qhhrly.cn/"
    redis-url: "qa-redis.lls.com"
    redis-db: 116
    MySql-Config:
      mysql-url: "mysql01.qa.lls.com"
      mysql-user: "root"
      mysql-pwd: 123456
    agw_message:
      username: "13049052666"
      password: "KJUWSFjt+kW5g+Irb9EVOmpFgqz66DdMHBFETmun4p2VtA1XAo92JpuZFhjKeDRmnNfP4SCxZEyXCSpgBFERmOrLI6eoxtxLYpwCjCs2Ev6yR82ZSooCUJGYIeBz6eNuq+sn84Sf5XrmW+fBsIekDlyzaZOoaBqoK0Jz/es0KWhQG/6JfGXEXh+hV5FDx8+9lgDuoIIwpuiUTZcchLT0teH9vXs8NCNcUNmrd8I9EGDegILkUea62TJUJhdQ1ZU70WgOazRCcz/trele1goX/Xrzlrs/3AuOcyrPE9/sVBDSFdzFGEhMiAo0FlvULTQ9zbCaKJKiQSqtcIdZbDiqyg=="
  v2:
    agw-url: "https://gdhscf-v2-agw.lianyirong.com.cn/"
    sp-url: "https://gdhscf-v2-sp.lianyirong.com.cn/"
    redis-url: "dev-redis.lls.com"
    redis-db: 129
    agw_message:
      username: "13611113333"
      password: "QvaNA4ZSkZkkig1jmMKXTIivQqWWjA3Ihb0i2dYvLJDAGQ+WnAnGgY++zMk/KjL+6YHMNMSblrCz18iwprEm2ttYJWtGby5q6M44knD0AAfRUiafmqMn8CL6Xm0zcgI2VUwts/vqe7oxxjnGt8LtVM2Ok6cQJVbkVy6JIOjfUQa576HN8VsF/jRagwS9ncysi43ADNLyRXtyErbhnazRRamn7bUn/oBpiMrUztxYhy/lTA2ZRt6KKl9sQlis4/rCnIPPS9oZQBQhcfyGDBHdXuRFh7S5g3Ng6RNzT3Zf8RvcnHkxykhRgNIxQKCvbkKSdWG8tI6Aa1J5MAEt0Jckvg=="

  uat:
    agw-url: "https://testagw.gdhchain.com.cn/"
    sp-url: "https://testpc.gdhchain.com.cn/"
    redis-url: "qa-redis.lls.com"
    agw_message:
      username: "13049052666"
      password: "KJUWSFjt+kW5g+Irb9EVOmpFgqz66DdMHBFETmun4p2VtA1XAo92JpuZFhjKeDRmnNfP4SCxZEyXCSpgBFERmOrLI6eoxtxLYpwCjCs2Ev6yR82ZSooCUJGYIeBz6eNuq+sn84Sf5XrmW+fBsIekDlyzaZOoaBqoK0Jz/es0KWhQG/6JfGXEXh+hV5FDx8+9lgDuoIIwpuiUTZcchLT0teH9vXs8NCNcUNmrd8I9EGDegILkUea62TJUJhdQ1ZU70WgOazRCcz/trele1goX/Xrzlrs/3AuOcyrPE9/sVBDSFdzFGEhMiAo0FlvULTQ9zbCaKJKiQSqtcIdZbDiqyg=="